### ISSUE TITLE
Fix phpdoc

### ISSUE THREAD

**Issue by williamdes** [MAXakaWIZARD/MoReader#3]
https://github.com/MAXakaWIZARD/MoReader/blob/91f6235353d5cddbb0498c8b64ce091de7e9b200/src/Reader.php#L280

http://php.net/manual/en/function.unpack.php

`unpack` returns `array`
phpdoc must be `array`

**Comment by MAXakaWIZARD** [comment]
Thanks! Fixed here: https://github.com/MAXakaWIZARD/MoReader/commit/08b4b7d7451c99d8222ffef21f8ea28aed21ff60

**Comment by MAXakaWIZARD** [comment]
New version was tagged.
